sudo: false
dist: bionic
language: python
addons:
  apt:
    packages:
      - python-dev        # Stream
      - cups              # Sensor cups
      - libcups2-dev      # Sensor cups
python:
  - "3.7"
before_install:
  - mv travis/travis_secrets.yaml secrets.yaml
  - mv travis/id_ed25519 .id_ed25519
install:
  - pip3 install homeassistant
  - pip3 install pycups            # Sensor cups
script:
  - hass -c . --script check_config
