- platform: manual
  name: "Home Alarm"
  code: !secret alarm_code
  arming_time: 30
  delay_time: 20
  trigger_time: 5
  disarmed:
    trigger_time: 0
- platform: manual
  name: "Garage Alarm"
  code: !secret alarm_code
  arming_time: 20
  delay_time: 0
  trigger_time: 5
  disarmed:
    trigger_time: 0
