#- alias: Send an email when the garage doorbell opens or if there is movement
#  trigger:
#  - platform: state
#    entity_id: binary_sensor.garage_door, binary_sensor.garage_pir
#    to: 'on'
#  action:
#    - service: notify.NOTIFIER_EMAIL
#      data:
#        title: 'Intruder alert'
#        message: 'Intruder alert at garage!'

- alias: 'Trigger alarm while armed away'
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_door
      to: 'open'
    - platform: state
      entity_id: binary_sensor.garage_pir
      to: 'active'
  condition:
    - condition: state
      entity_id: alarm_control_panel.garage_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.garage_alarm

################################
### Garage alarm triggered
################################

- alias: Triggered Flash
  trigger:
    platform: state
    entity_id: alarm_control_panel.garage_alarm
    state: 'triggered'
  action:
    - service: notify.NOTIFIER_EMAIL
      data:
        title: 'Garage Alarm Triggered'
        message: 'Garage Alarm Triggered: {{ now().strftime("%Y%m%d-%H%M%S") }}'

################################
### Garage alarm off
################################

- alias: Disarmed Off
  trigger:
    platform: state
    entity_id: alarm_control_panel.garage_alarm
    state: 'disarmed'
  action:
    - service: notify.NOTIFIER_EMAIL
      data:
        title: 'Garage Alarm Reset'
        message: 'Garage Alarm Reset {{ now().strftime("%Y%m%d-%H%M%S") }}'

