#- alias: Send an email when the garage doorbell opens or if there is movement
#  trigger:
#  - platform: state
#    entity_id: binary_sensor.garage_door, binary_sensor.garage_pir
#    to: 'on'
#  action:
#    - service: notify.NOTIFIER_EMAIL
#      data:
#        title: 'Intruder alert'
#        message: 'Intruder alert at garage!'

################################
###       Garage Alarm       ###
################################

- alias: 'Garage Alarm trigger while Armed'
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_door
      to: 'on'
    - platform: state
      entity_id: binary_sensor.garage_pir
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.garage_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.garage_alarm

- alias: 'Garage Alarm Triggered'
  trigger:
    platform: state
    entity_id: alarm_control_panel.garage_alarm
    to: 'triggered'
  action:
    - service: notify.NOTIFIER_EMAIL
      data:
        title: 'Garage Alarm Triggered'
        message: |
          Garage Alarm Triggered: {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
          
          Door: {{ states.binary_sensor.garage_door.state }}
          PIR: {{ states.binary_sensor.garage_pir.state }}
    - delay:
        seconds: 10
    - service: switch.turn_on
      data:
        entity_id: switch.garage_table_light
    - delay:
        seconds: 3
    - service: switch.turn_off
      data:
        entity_id: switch.garage_table_light
    - delay:
        seconds: 3
    - service: switch.turn_on
      data:
        entity_id: switch.garage_table_light
    - delay:
        seconds: 3
    - service: switch.turn_off
      data:
        entity_id: switch.garage_table_light

- alias: 'Garage Alarm Disarmed'
  trigger:
    platform: state
    entity_id: alarm_control_panel.garage_alarm
    to: 'disarmed'
  action:
    - service: notify.NOTIFIER_EMAIL
      data:
        title: 'Garage Alarm Disarmed'
        message: 'Garage Alarm Disarmed {{ now().strftime("%Y-%m-%d %H:%M:%S") }}'
