# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

###################################################
#     Home Assistant Main Configuration File      #
###################################################
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 215
  unit_system: metric
  time_zone: Europe/Bratislava
  internal_url: !secret internal_url
  # https://www.home-assistant.io/docs/configuration/customizing-devices/
  customize: !include customize.yaml
  # https://home-assistant.io/docs/configuration/packages/
  packages: !include_dir_named packages

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
notify: !include notify.yaml

asuswrt:
  host: 192.168.24.1
  username: !secret asuswrt_username
  protocol: ssh
  ssh_key: !secret asuswrt_sshkey
  sensors:
    - devices
    - upload
    - download
    - upload_speed
    - download_speed

#ffmpeg:
#  ffmpeg_bin: /usr/bin/ffmpeg
#
#camera:
#  - platform: ffmpeg
#    name: Garage Camera
#    input: -rtsp_transport udp -i rtsp://admin:x8Gpaxesbg325iJA@192.168.24.250:554/onvif1
#  - platform: onvif
#    host: 192.168.24.250
#    name: Garage CAM
#    username: admin
#    password: x8Gpaxesbg325iJA
#    port: 554