###################################################
#     Home Assistant Main Configuration File      #
###################################################
homeassistant:
  customize: !include customize.yaml
  # https://home-assistant.io/docs/configuration/packages/
  packages: !include_dir_named packages

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
notify: !include notify.yaml

asuswrt:
  host: 192.168.24.1
  username: !secret asuswrt_username
  protocol: ssh
  ssh_key: !secret asuswrt_sshkey
  sensors:
    - devices
    - upload
    - download
    - upload_speed
    - download_speed
