# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

###################################################
#     Home Assistant Main Configuration File      #
###################################################
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 215
  unit_system: metric
  time_zone: Europe/Bratislava
  internal_url: !secret internal_url
  # https://www.home-assistant.io/docs/configuration/customizing-devices/
  customize: !include customize.yaml
  # https://home-assistant.io/docs/configuration/packages/
  packages: !include_dir_named packages

frontend:
  themes: !include_dir_merge_named themes

#lovelace:
#  mode: yaml

# Text to speech
tts:
  - platform: google_translate

group: !include_dir_merge_named groups/
alarm_control_panel: !include alarm.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
notify: !include notify.yaml
recorder: !include recorder.yaml

asuswrt:
  host: 192.168.24.1
  username: !secret asuswrt_username
  protocol: ssh
  ssh_key: !secret asuswrt_sshkey
  sensors:
    - devices
    - upload
    - download
    - upload_speed
    - download_speed

volkswagencarnet:
    username: !secret volkswagen_carnet_username
    password: !secret volkswagen_carnet_password
    scandinavian_miles: false
    scan_interval:
        minutes: 15
    name:
        wvw1234567812356: 'Sportsvan'
    resources: # Optional
        - position
        - distance
        - service_inspection
        - oil_inspection
        - fuel_level
        - door_locked
        - trunk_locked
        - last_connected
        - request_in_progress
        - trip_last_average_speed
        - trip_last_average_fuel_consumption
        - trip_last_duration
