################################
###       Garage Alarm       ###
################################

- alias: 'Garage Alarm trigger while Armed'
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_door
      to: 'on'
    - platform: state
      entity_id: binary_sensor.garage_pir
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.garage_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.garage_alarm

- alias: 'Garage Alarm Armed away'
  trigger:
    platform: state
    entity_id: alarm_control_panel.garage_alarm
    to: 'armed_away'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.gtl_light_2
    - service: switch.turn_off
      data:
        entity_id: switch.gnmcu_table_led_stripe
    - delay:
        seconds: 45
    - service: switch.turn_off
      data:
        entity_id: switch.gv_power
 
- alias: 'Garage Alarm Triggered'
  trigger:
    platform: state
    entity_id: alarm_control_panel.garage_alarm
    to: 'triggered'
  action:
    - service: notify.NOTIFIER_EMAIL
      data:
        title: 'Garage Alarm Triggered'
        message: |
          Garage Alarm Triggered: {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
          
          Door: {{ states.binary_sensor.garage_door.state }}
          PIR: {{ states.binary_sensor.garage_pir.state }}
    
    - service: switch.turn_on
      data:
        entity_id: switch.gv_power
    - service: switch.turn_on
      data:
        entity_id: switch.gtl_light_2
    - service: switch.turn_off
      data:
        entity_id: switch.gnmcu_table_led_stripe
    - delay:
        seconds: 5

    - service: switch.turn_off
      data:
        entity_id: switch.gtl_light_2
    - service: switch.turn_on
      data:
        entity_id: switch.gnmcu_table_led_stripe
    - delay:
        seconds: 2

    - service: switch.turn_on
      data:
        entity_id: switch.gtl_light_2
    - service: switch.turn_off
      data:
        entity_id: switch.gnmcu_table_led_stripe
    - delay:
        seconds: 2

    - service: switch.turn_off
      data:
        entity_id: switch.gtl_light_2
    - service: switch.turn_on
      data:
        entity_id: switch.gnmcu_table_led_stripe
    - delay:
        seconds: 1

    - service: switch.turn_on
      data:
        entity_id: switch.gtl_light_2
    - service: switch.turn_off
      data:
        entity_id: switch.gnmcu_table_led_stripe
    - delay:
        seconds: 1

    - service: switch.turn_off
      data:
        entity_id: switch.gtl_light_2
    - service: switch.turn_on
      data:
        entity_id: switch.gnmcu_table_led_stripe
    - delay:
        seconds: 1

    - service: camera.snapshot
      data:
        entity_id: camera.camera.garage_cam_1_mainstream
        filename: "/config/www/cam_captures/garage_cam_1_{{ now().strftime('%Y-%m-%d_%H-%M-%S') }}.jpg"
    - service: switch.turn_off
      data:
        entity_id: switch.gtl_light_2
    
    - delay:
        minutes: 5
    - service: switch.turn_off
      data:
        entity_id: switch.gv_power
 
- alias: 'Garage Alarm Disarmed'
  trigger:
    platform: state
    entity_id: alarm_control_panel.garage_alarm
    to: 'disarmed'
  action:
    - service: notify.NOTIFIER_EMAIL
      data:
        title: 'Garage Alarm Disarmed'
        message: 'Garage Alarm Disarmed {{ now().strftime("%Y-%m-%d %H:%M:%S") }}'
