esphome:
  name: garage_main_switch
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_vault_ssid
  password: !secret wifi_vault_password
  domain: !secret wifi_vault_domain

  # Set IP manually (otherwise HA fails to connect often)
  manual_ip:
    static_ip: !secret gms_ip
    gateway: !secret wifi_vault_gateway
    subnet: !secret wifi_vault_subnet
    dns1: !secret wifi_vault_dns
  # use_address: !secret gms_old_ip

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "GMS Fallback Hotspot"
    password: !secret gms_fallback_ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret gms_api_password

ota:
  password: !secret gms_ota_password

# Enable Web server.
# web_server:
#   port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Garage Main Switch Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Garage Main Switch Power"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

uart:
  rx_pin: RX
  baud_rate: 4800

# Sensors with general information.
sensor:
  - platform: cse7766
    current:
      name: "Garage Main Switch Current"
    voltage:
      name: "Garage Main Switch Voltage"
    power:
      name: "Garage Main Switch Power"

  # Uptime sensor.
  - platform: uptime
    name: "Garage Main Switch Uptime"

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: "Garage Main Switch WiFi Signal"
    update_interval: 60s
