substitutions:
  devicename: gtl
  upper_devicename: GTL
  device_verbose_name: "Garage Table Light"
  platform: ESP8266
  board: esp8285
  api_password: !secret gtl_api_password
  static_ip: !secret gtl_ip
  fallback_ap_password: !secret gtl_fallback_ap_password

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${upper_devicename} Button"
    on_press:
      - switch.toggle: "${devicename}_relay"

switch:
  - platform: gpio
    name: "${upper_devicename} Light"
    id: "${devicename}_relay"
    pin: GPIO12

status_led:
  pin:
    number: GPIO13
    inverted: yes
