esphome:
  name: garage_ventilation
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_vault_ssid
  password: !secret wifi_vault_password
  domain: !secret wifi_vault_domain

  # Set IP manually (otherwise HA fails to connect often)
  manual_ip:
    static_ip: !secret gv_ip
    gateway: !secret wifi_vault_gateway
    subnet: !secret wifi_vault_subnet
    dns1: !secret wifi_vault_dns
  # use_address: !secret gv_old_ip

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "GV Fallback Hotspot"
    password: !secret gv_fallback_ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret gv_api_password

ota:
  password: !secret gv_ota_password

# Enable Web server.
# web_server:
#   port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Garage Ventilation Button"
    on_press:
      - switch.toggle: relay

  - platform: status
    name: "Garage Ventilation Status"

switch:
  - platform: gpio
    name: "Garage Ventilation Power"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: "Garage Ventilation Uptime"
    filters:
      - lambda: return x / 3600.0;
    unit_of_measurement: "hours"
    accuracy_decimals: 2

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: "Garage Ventilation WiFi Signal"
    update_interval: 60s

text_sensor:
  - platform: version
    name: "GV ESPHome Version"
    hide_timestamp: True
