esphome:
  name: garage_table_light
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_vault_ssid
  password: !secret wifi_vault_password
  domain: !secret wifi_vault_domain

  # Set IP manually (otherwise HA fails to connect often)
  manual_ip:
    static_ip: !secret gtl_ip
    gateway: !secret wifi_vault_gateway
    subnet: !secret wifi_vault_subnet
    dns1: !secret wifi_vault_dns
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "GTL Fallback Hotspot"
    password: !secret gtl_fallback_ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret gtl_api_password

ota:
  password: !secret gtl_ota_password

# Enable Web server.
# web_server:
#   port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Garage Table Light Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Garage Table Light"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: "Garage Table Light Uptime"

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: "Garage Table Light WiFi Signal"
    update_interval: 60s

