substitutions:
  devicename: gms
  upper_devicename: GMS
  device_verbose_name: "Garage Main Switch"
  platform: ESP8266
  board: esp8285
  api_password: !secret gms_api_password
  static_ip: !secret gms_ip
  fallback_ap_password: !secret gms_fallback_ap_password

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${upper_devicename} Button"
    on_press:
      - switch.toggle: "${devicename}_relay"

switch:
  - platform: gpio
    name: "${upper_devicename} Power"
    id: "${devicename}_relay"
    pin: GPIO12

status_led:
  pin:
    number: GPIO13
    inverted: yes

uart:
  rx_pin: RX
  baud_rate: 4800

# Sensors with general information.
sensor:
  - platform: cse7766
    current:
      name: "${upper_devicename} Current"
    voltage:
      name: "${upper_devicename} Voltage"
    power:
      name: "${upper_devicename} Power"
