##################################################
## Customize
##################################################
binary_sensor:
  - platform: mqtt
    name: "Garage PIR"
    state_topic: "garage/pir/status"
    device_class: motion
