##################################################
## List of all motion sensors
##################################################
binary_sensor:
  - platform: mqtt
    name: "Garage PIR"
    device_class: motion
    state_topic: "garage/pir/1/status"
    availability_topic: "garage/pir/1/availability"
    payload_available: 1
    payload_not_available: 0
    payload_on: 1
    payload_off: 0
    off_delay: 60