##################################################
## List of all temperature/humidity sensors
##################################################
sensor:
  - platform: mqtt
    unique_id: doorway-dht-temp
    name: "Doorway TEMP"
    device_class: temperature
    unit_of_measurement: "°C"
    state_topic: "home/doorway/dht/temperature"
    availability_topic: "home/doorway/dht/availability"
    payload_available: 1
    payload_not_available: 0
    expire_after: 900
  - platform: mqtt
    unique_id: doorway-dht-hum
    name: "Doorway HUM"
    device_class: humidity
    unit_of_measurement: "%"
    state_topic: "home/doorway/dht/humidity"
    availability_topic: "home/doorway/dht/availability"
    payload_available: 1
    payload_not_available: 0
    expire_after: 900
  - platform: mqtt
    unique_id: garage-indoor-dht-temp
    name: "Garage TEMP"
    device_class: temperature
    unit_of_measurement: "°C"
    state_topic: "garage/indoor/dht/temperature"
    availability_topic: "garage/indoor/dht/availability"
    payload_available: 1
    payload_not_available: 0
    expire_after: 900
  - platform: mqtt
    unique_id: garage-indoor-dht-hum
    name: "Garage HUM"
    device_class: humidity
    unit_of_measurement: "%"
    state_topic: "garage/indoor/dht/humidity"
    availability_topic: "garage/indoor/dht/availability"
    payload_available: 1
    payload_not_available: 0
    expire_after: 900