##################################################
## List of all temperature/humidity sensors
##################################################
sensor:
  - platform: broadlink
    name: "Livingroom"
    scan_interval: 60
    host: !secret broadlink_ip
    mac: !secret broadlink_mac
    type: rm4_pro
    monitored_conditions:
      - temperature
      - humidity
  - platform: mqtt
    unique_id: doorway-dht-temp
    name: "Doorway Temperature"
    device_class: temperature
    unit_of_measurement: "°C"
    state_topic: "home/doorway/dht/temperature"
    availability_topic: "home/doorway/dht/availability"
    payload_available: 1
    payload_not_available: 0
    expire_after: 900
  - platform: mqtt
    unique_id: doorway-dht-hum
    name: "Doorway Humidity"
    device_class: humidity
    unit_of_measurement: "%"
    state_topic: "home/doorway/dht/humidity"
    availability_topic: "home/doorway/dht/availability"
    payload_available: 1
    payload_not_available: 0
    expire_after: 900
  - platform: mqtt
    unique_id: garage-indoor-dht-temp
    name: "Garage Temperature"
    device_class: temperature
    unit_of_measurement: "°C"
    state_topic: "garage/indoor/dht/temperature"
    availability_topic: "garage/indoor/dht/availability"
    payload_available: 1
    payload_not_available: 0
    expire_after: 900
  - platform: mqtt
    unique_id: garage-indoor-dht-hum
    name: "Garage Humidity"
    device_class: humidity
    unit_of_measurement: "%"
    state_topic: "garage/indoor/dht/humidity"
    availability_topic: "garage/indoor/dht/availability"
    payload_available: 1
    payload_not_available: 0
    expire_after: 900